[2024-12-02T16:03:10.287+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T16:03:10.296+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tv_schedule_scraper.scrape_tv_schedule manual__2024-12-02T15:58:08.803092+00:00 [queued]>
[2024-12-02T16:03:10.301+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tv_schedule_scraper.scrape_tv_schedule manual__2024-12-02T15:58:08.803092+00:00 [queued]>
[2024-12-02T16:03:10.301+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-02T16:03:10.308+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_tv_schedule> on 2024-12-02 15:58:08.803092+00:00
[2024-12-02T16:03:10.311+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-02T16:03:10.312+0000] {standard_task_runner.py:72} INFO - Started process 182 to run task
[2024-12-02T16:03:10.313+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tv_schedule_scraper', 'scrape_tv_schedule', 'manual__2024-12-02T15:58:08.803092+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/dag_rtve.py', '--cfg-path', '/tmp/tmptuw3qqv2']
[2024-12-02T16:03:10.315+0000] {standard_task_runner.py:105} INFO - Job 249: Subtask scrape_tv_schedule
[2024-12-02T16:03:10.340+0000] {task_command.py:467} INFO - Running <TaskInstance: tv_schedule_scraper.scrape_tv_schedule manual__2024-12-02T15:58:08.803092+00:00 [running]> on host c2dfb6fa46f1
[2024-12-02T16:03:10.378+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tv_schedule_scraper' AIRFLOW_CTX_TASK_ID='scrape_tv_schedule' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T15:58:08.803092+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T15:58:08.803092+00:00'
[2024-12-02T16:03:10.378+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T16:03:14.176+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_rtve.py", line 39, in scrape_tv_schedule
    ).click()
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (668, 626)
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x55b2ab7c4ca7 <unknown>
#1 0x55b2ab49bc9c <unknown>
#2 0x55b2ab4e665d <unknown>
#3 0x55b2ab4e4dfd <unknown>
#4 0x55b2ab4e30b0 <unknown>
#5 0x55b2ab4e26eb <unknown>
#6 0x55b2ab4d7f1a <unknown>
#7 0x55b2ab502f86 <unknown>
#8 0x55b2ab4d7912 <unknown>
#9 0x55b2ab503132 <unknown>
#10 0x55b2ab51ff16 <unknown>
#11 0x55b2ab502ce7 <unknown>
#12 0x55b2ab4d56b1 <unknown>
#13 0x55b2ab4d64c6 <unknown>
#14 0x55b2ab79255a <unknown>
#15 0x55b2ab7958ea <unknown>
#16 0x55b2ab795393 <unknown>
#17 0x55b2ab795d79 <unknown>
#18 0x55b2ab782b2f <unknown>
#19 0x55b2ab796134 <unknown>
#20 0x55b2ab76b5aa <unknown>
#21 0x55b2ab7b5459 <unknown>
#22 0x55b2ab7b5646 <unknown>
#23 0x55b2ab7c4193 <unknown>
#24 0x7ff1dea4a134 <unknown>

[2024-12-02T16:03:14.185+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tv_schedule_scraper, task_id=scrape_tv_schedule, run_id=manual__2024-12-02T15:58:08.803092+00:00, execution_date=20241202T155808, start_date=20241202T160310, end_date=20241202T160314
[2024-12-02T16:03:14.191+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T16:03:14.192+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 249 for task scrape_tv_schedule (Message: element click intercepted: Element is not clickable at point (668, 626)
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x55b2ab7c4ca7 <unknown>
#1 0x55b2ab49bc9c <unknown>
#2 0x55b2ab4e665d <unknown>
#3 0x55b2ab4e4dfd <unknown>
#4 0x55b2ab4e30b0 <unknown>
#5 0x55b2ab4e26eb <unknown>
#6 0x55b2ab4d7f1a <unknown>
#7 0x55b2ab502f86 <unknown>
#8 0x55b2ab4d7912 <unknown>
#9 0x55b2ab503132 <unknown>
#10 0x55b2ab51ff16 <unknown>
#11 0x55b2ab502ce7 <unknown>
#12 0x55b2ab4d56b1 <unknown>
#13 0x55b2ab4d64c6 <unknown>
#14 0x55b2ab79255a <unknown>
#15 0x55b2ab7958ea <unknown>
#16 0x55b2ab795393 <unknown>
#17 0x55b2ab795d79 <unknown>
#18 0x55b2ab782b2f <unknown>
#19 0x55b2ab796134 <unknown>
#20 0x55b2ab76b5aa <unknown>
#21 0x55b2ab7b5459 <unknown>
#22 0x55b2ab7b5646 <unknown>
#23 0x55b2ab7c4193 <unknown>
#24 0x7ff1dea4a134 <unknown>
; 182)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_rtve.py", line 39, in scrape_tv_schedule
    ).click()
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (668, 626)
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x55b2ab7c4ca7 <unknown>
#1 0x55b2ab49bc9c <unknown>
#2 0x55b2ab4e665d <unknown>
#3 0x55b2ab4e4dfd <unknown>
#4 0x55b2ab4e30b0 <unknown>
#5 0x55b2ab4e26eb <unknown>
#6 0x55b2ab4d7f1a <unknown>
#7 0x55b2ab502f86 <unknown>
#8 0x55b2ab4d7912 <unknown>
#9 0x55b2ab503132 <unknown>
#10 0x55b2ab51ff16 <unknown>
#11 0x55b2ab502ce7 <unknown>
#12 0x55b2ab4d56b1 <unknown>
#13 0x55b2ab4d64c6 <unknown>
#14 0x55b2ab79255a <unknown>
#15 0x55b2ab7958ea <unknown>
#16 0x55b2ab795393 <unknown>
#17 0x55b2ab795d79 <unknown>
#18 0x55b2ab782b2f <unknown>
#19 0x55b2ab796134 <unknown>
#20 0x55b2ab76b5aa <unknown>
#21 0x55b2ab7b5459 <unknown>
#22 0x55b2ab7b5646 <unknown>
#23 0x55b2ab7c4193 <unknown>
#24 0x7ff1dea4a134 <unknown>

[2024-12-02T16:03:14.216+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-02T16:03:14.224+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-02T16:03:14.225+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
