[2024-12-15T17:30:16.569+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T17:30:16.578+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: a3media_schedule_scraper.push_all_in_one scheduled__2024-12-15T11:30:00+00:00 [queued]>
[2024-12-15T17:30:16.582+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: a3media_schedule_scraper.push_all_in_one scheduled__2024-12-15T11:30:00+00:00 [queued]>
[2024-12-15T17:30:16.583+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2024-12-15T17:30:16.590+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): push_all_in_one> on 2024-12-15 11:30:00+00:00
[2024-12-15T17:30:16.593+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5689) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-15T17:30:16.594+0000] {standard_task_runner.py:72} INFO - Started process 5690 to run task
[2024-12-15T17:30:16.594+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'a3media_schedule_scraper', 'push_all_in_one', 'scheduled__2024-12-15T11:30:00+00:00', '--job-id', '2550', '--raw', '--subdir', 'DAGS_FOLDER/dag_atresmedia.py', '--cfg-path', '/tmp/tmp5hrzh37g']
[2024-12-15T17:30:16.595+0000] {standard_task_runner.py:105} INFO - Job 2550: Subtask push_all_in_one
[2024-12-15T17:30:16.621+0000] {task_command.py:467} INFO - Running <TaskInstance: a3media_schedule_scraper.push_all_in_one scheduled__2024-12-15T11:30:00+00:00 [running]> on host b605548c7b8b
[2024-12-15T17:30:16.662+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='a3media_schedule_scraper' AIRFLOW_CTX_TASK_ID='push_all_in_one' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-15T11:30:00+00:00'
[2024-12-15T17:30:16.663+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T17:30:20.526+0000] {logging_mixin.py:190} INFO - Error: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "422"}
[2024-12-15T17:30:20.527+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-15T17:30:20.533+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T17:30:20.533+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=a3media_schedule_scraper, task_id=push_all_in_one, run_id=scheduled__2024-12-15T11:30:00+00:00, execution_date=20241215T113000, start_date=20241215T173016, end_date=20241215T173020
[2024-12-15T17:30:20.578+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-15T17:30:20.586+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T17:30:20.587+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
