[2024-12-02T17:09:08.216+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T17:09:08.225+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tv_schedule_scraper.scrape_tv_schedule manual__2024-12-02T17:09:06.852561+00:00 [queued]>
[2024-12-02T17:09:08.231+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tv_schedule_scraper.scrape_tv_schedule manual__2024-12-02T17:09:06.852561+00:00 [queued]>
[2024-12-02T17:09:08.231+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-02T17:09:08.238+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_tv_schedule> on 2024-12-02 17:09:06.852561+00:00
[2024-12-02T17:09:08.241+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-02T17:09:08.243+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2024-12-02T17:09:08.242+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tv_schedule_scraper', 'scrape_tv_schedule', 'manual__2024-12-02T17:09:06.852561+00:00', '--job-id', '344', '--raw', '--subdir', 'DAGS_FOLDER/dag_rtve.py', '--cfg-path', '/tmp/tmpz0qraf03']
[2024-12-02T17:09:08.244+0000] {standard_task_runner.py:105} INFO - Job 344: Subtask scrape_tv_schedule
[2024-12-02T17:09:08.269+0000] {task_command.py:467} INFO - Running <TaskInstance: tv_schedule_scraper.scrape_tv_schedule manual__2024-12-02T17:09:06.852561+00:00 [running]> on host c2dfb6fa46f1
[2024-12-02T17:09:08.310+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tv_schedule_scraper' AIRFLOW_CTX_TASK_ID='scrape_tv_schedule' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T17:09:06.852561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T17:09:06.852561+00:00'
[2024-12-02T17:09:08.311+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T17:09:11.986+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_rtve.py", line 41, in scrape_tv_schedule
    ).click()
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (668, 629)
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x5590eaf8fca7 <unknown>
#1 0x5590eac66c9c <unknown>
#2 0x5590eacb165d <unknown>
#3 0x5590eacafdfd <unknown>
#4 0x5590eacae0b0 <unknown>
#5 0x5590eacad6eb <unknown>
#6 0x5590eaca2f1a <unknown>
#7 0x5590eaccdf86 <unknown>
#8 0x5590eaca2912 <unknown>
#9 0x5590eacce132 <unknown>
#10 0x5590eaceaf16 <unknown>
#11 0x5590eaccdce7 <unknown>
#12 0x5590eaca06b1 <unknown>
#13 0x5590eaca14c6 <unknown>
#14 0x5590eaf5d55a <unknown>
#15 0x5590eaf608ea <unknown>
#16 0x5590eaf60393 <unknown>
#17 0x5590eaf60d79 <unknown>
#18 0x5590eaf4db2f <unknown>
#19 0x5590eaf61134 <unknown>
#20 0x5590eaf365aa <unknown>
#21 0x5590eaf80459 <unknown>
#22 0x5590eaf80646 <unknown>
#23 0x5590eaf8f193 <unknown>
#24 0x7f92e204e134 <unknown>

[2024-12-02T17:09:11.996+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=tv_schedule_scraper, task_id=scrape_tv_schedule, run_id=manual__2024-12-02T17:09:06.852561+00:00, execution_date=20241202T170906, start_date=20241202T170908, end_date=20241202T170911
[2024-12-02T17:09:12.004+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T17:09:12.005+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 344 for task scrape_tv_schedule (Message: element click intercepted: Element is not clickable at point (668, 629)
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x5590eaf8fca7 <unknown>
#1 0x5590eac66c9c <unknown>
#2 0x5590eacb165d <unknown>
#3 0x5590eacafdfd <unknown>
#4 0x5590eacae0b0 <unknown>
#5 0x5590eacad6eb <unknown>
#6 0x5590eaca2f1a <unknown>
#7 0x5590eaccdf86 <unknown>
#8 0x5590eaca2912 <unknown>
#9 0x5590eacce132 <unknown>
#10 0x5590eaceaf16 <unknown>
#11 0x5590eaccdce7 <unknown>
#12 0x5590eaca06b1 <unknown>
#13 0x5590eaca14c6 <unknown>
#14 0x5590eaf5d55a <unknown>
#15 0x5590eaf608ea <unknown>
#16 0x5590eaf60393 <unknown>
#17 0x5590eaf60d79 <unknown>
#18 0x5590eaf4db2f <unknown>
#19 0x5590eaf61134 <unknown>
#20 0x5590eaf365aa <unknown>
#21 0x5590eaf80459 <unknown>
#22 0x5590eaf80646 <unknown>
#23 0x5590eaf8f193 <unknown>
#24 0x7f92e204e134 <unknown>
; 105)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_rtve.py", line 41, in scrape_tv_schedule
    ).click()
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (668, 629)
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x5590eaf8fca7 <unknown>
#1 0x5590eac66c9c <unknown>
#2 0x5590eacb165d <unknown>
#3 0x5590eacafdfd <unknown>
#4 0x5590eacae0b0 <unknown>
#5 0x5590eacad6eb <unknown>
#6 0x5590eaca2f1a <unknown>
#7 0x5590eaccdf86 <unknown>
#8 0x5590eaca2912 <unknown>
#9 0x5590eacce132 <unknown>
#10 0x5590eaceaf16 <unknown>
#11 0x5590eaccdce7 <unknown>
#12 0x5590eaca06b1 <unknown>
#13 0x5590eaca14c6 <unknown>
#14 0x5590eaf5d55a <unknown>
#15 0x5590eaf608ea <unknown>
#16 0x5590eaf60393 <unknown>
#17 0x5590eaf60d79 <unknown>
#18 0x5590eaf4db2f <unknown>
#19 0x5590eaf61134 <unknown>
#20 0x5590eaf365aa <unknown>
#21 0x5590eaf80459 <unknown>
#22 0x5590eaf80646 <unknown>
#23 0x5590eaf8f193 <unknown>
#24 0x7f92e204e134 <unknown>

[2024-12-02T17:09:12.026+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-02T17:09:12.037+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-02T17:09:12.038+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
