[2024-12-06T12:53:44.393+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T12:53:44.404+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-02-21T12:00:00+00:00 [queued]>
[2024-12-06T12:53:44.411+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-02-21T12:00:00+00:00 [queued]>
[2024-12-06T12:53:44.412+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2024-12-06T12:53:44.420+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): PushAllInOne> on 2024-02-21 12:00:00+00:00
[2024-12-06T12:53:44.424+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=602) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T12:53:44.425+0000] {standard_task_runner.py:72} INFO - Started process 612 to run task
[2024-12-06T12:53:44.426+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'telemadrid_schedule_scraper_v2', 'PushAllInOne', 'scheduled__2024-02-21T12:00:00+00:00', '--job-id', '1139', '--raw', '--subdir', 'DAGS_FOLDER/dag_telemadrid_v2.py', '--cfg-path', '/tmp/tmpkejb2agf']
[2024-12-06T12:53:44.427+0000] {standard_task_runner.py:105} INFO - Job 1139: Subtask PushAllInOne
[2024-12-06T12:53:44.464+0000] {task_command.py:467} INFO - Running <TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-02-21T12:00:00+00:00 [running]> on host 01ebcafa06b4
[2024-12-06T12:53:44.532+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telemadrid_schedule_scraper_v2' AIRFLOW_CTX_TASK_ID='PushAllInOne' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-21T12:00:00+00:00'
[2024-12-06T12:53:44.534+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T12:53:49.916+0000] {logging_mixin.py:190} INFO - Error: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "422"}
[2024-12-06T12:53:49.917+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-06T12:53:49.923+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T12:53:49.923+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=telemadrid_schedule_scraper_v2, task_id=PushAllInOne, run_id=scheduled__2024-02-21T12:00:00+00:00, execution_date=20240221T120000, start_date=20241206T125344, end_date=20241206T125349
[2024-12-06T12:53:49.995+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-06T12:53:50.004+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T12:53:50.005+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
