[2024-12-15T11:30:20.234+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T11:30:20.254+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: a3media_schedule_scraper.push_all_in_one scheduled__2024-12-15T05:30:00+00:00 [queued]>
[2024-12-15T11:30:20.269+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: a3media_schedule_scraper.push_all_in_one scheduled__2024-12-15T05:30:00+00:00 [queued]>
[2024-12-15T11:30:20.270+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2024-12-15T11:30:20.286+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): push_all_in_one> on 2024-12-15 05:30:00+00:00
[2024-12-15T11:30:20.291+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=872) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-15T11:30:20.293+0000] {standard_task_runner.py:72} INFO - Started process 873 to run task
[2024-12-15T11:30:20.293+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'a3media_schedule_scraper', 'push_all_in_one', 'scheduled__2024-12-15T05:30:00+00:00', '--job-id', '2530', '--raw', '--subdir', 'DAGS_FOLDER/dag_atresmedia.py', '--cfg-path', '/tmp/tmpdo9uglm9']
[2024-12-15T11:30:20.295+0000] {standard_task_runner.py:105} INFO - Job 2530: Subtask push_all_in_one
[2024-12-15T11:30:20.335+0000] {task_command.py:467} INFO - Running <TaskInstance: a3media_schedule_scraper.push_all_in_one scheduled__2024-12-15T05:30:00+00:00 [running]> on host b605548c7b8b
[2024-12-15T11:30:20.411+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='a3media_schedule_scraper' AIRFLOW_CTX_TASK_ID='push_all_in_one' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T05:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-15T05:30:00+00:00'
[2024-12-15T11:30:20.412+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T11:30:24.430+0000] {logging_mixin.py:190} INFO - Error: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "422"}
[2024-12-15T11:30:24.432+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-15T11:30:24.441+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T11:30:24.442+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=a3media_schedule_scraper, task_id=push_all_in_one, run_id=scheduled__2024-12-15T05:30:00+00:00, execution_date=20241215T053000, start_date=20241215T113020, end_date=20241215T113024
[2024-12-15T11:30:24.482+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-15T11:30:24.533+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T11:30:24.551+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
